/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import apiResourcesRouteInjectable from "./api-resources-route.injectable";
import navigateToApiResourcesInjectable from "./navigate-to-api-resources.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(apiResourcesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToApiResourcesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
