/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import rbacVisualizerRouteComponentInjectable from "./rbac-visualizer-route-component.injectable";
import rbacVisualizerSidebarItemInjectable from "./rbac-visualizer-sidebar-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(rbacVisualizerRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(rbacVisualizerSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
