/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import apiServiceApiInjectable from "./api-service.api.injectable";
import apiServicesRouteComponentInjectable from "./api-services-route-component.injectable";
import apiServicesSidebarItemInjectable from "./sidebar-item.injectable";
import apiServiceStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(apiServiceApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(apiServiceStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(apiServicesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(apiServicesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
