/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToRbacVisualizerInjectable from "./navigate-to-rbac-visualizer.injectable";
import rbacVisualizerRouteInjectable from "./rbac-visualizer-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToRbacVisualizerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(rbacVisualizerRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
