/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import apiResourceGroupsInjectable from "./api-resource-groups.injectable";
import apiResourceGroupsSidebarItemsComputedInjectable from "./api-resource-groups-sidebar-items-computed.injectable";
import apiResourceGroupsSidebarItemsRegistratorInjectable from "./api-resource-groups-sidebar-items-registrator.injectable";
import apiResourcesRouteComponentInjectable from "./api-resources-route-component.injectable";
import apiResourcesSidebarItemInjectable from "./sidebar-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(apiResourceGroupsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(apiResourceGroupsSidebarItemsComputedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(apiResourceGroupsSidebarItemsRegistratorInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(apiResourcesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(apiResourcesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
